# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/sim2sim/policy/policy.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/N2/mjcf/N2_10dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [80, 80, 120, 120, 20, 80, 80, 120, 120, 20]
kds: [5, 5, 5, 5, 2, 5, 5, 5, 5, 2]

default_angles: [0.0, 0.0, -0.1495, 0.3215, -0.1720,
                 0.0, 0.0, -0.1495, 0.3215, -0.1720]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 1.0]
num_actions: 10 #18
num_single_obs: 39 #63
frame_stack: 1 #5
num_obs:  39 #num_single_obs * frame_stack #315

cmd_init: [0, 0, 0]